INSERT INTO ALBUMTABLE VALUES('1','Hybrid Theory','1','2000');
INSERT INTO ALBUMTABLE VALUES('2','Meteora','1','2003');
INSERT INTO ALBUMTABLE VALUES('3','Minutes To Midnight','1','2000');
INSERT INTO ALBUMTABLE VALUES('1','Curb','2','1996');
INSERT INTO ALBUMTABLE VALUES('2','The State','2','1996');
INSERT INTO ALBUMTABLE VALUES('3','Silver State Up','2','2001');
INSERT INTO ALBUMTABLE VALUES('1','No Name Face','3','2000');
INSERT INTO ALBUMTABLE VALUES('2','Stanley Climbfall','3','2002');
INSERT INTO ALBUMTABLE VALUES('3','Lifehouse','3','2005');
